convert: allow empty files to be parsed (#1153)
Since https://github.com/pulumi/pulumi/pull/23948, `pulumi do` can send
empty files to the converter. Yaml currently errors out on that, even
though it can be a valid state for `pulumi do` to be in (e.g. if only
flags are passed for provider configuration, but no file):

```
    error: parse provider file: <no provider file>:0,0-0: unexpected node kind 0;
```

Fix this by not erroring out just because we try to convert an empty
file.